# Generated by Neurodocker and Reproenv.
# need to set fsl variabls
# need to do. for mrtrix3 mrdegibbs

#apt-get update
#apt-get install libfftw3-dev

FROM debian:buster-slim
ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
#ADD ixi bids
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bzip2 \
           ca-certificates \
           curl \
    && rm -rf /var/lib/apt/lists/* \
    #&& mkdir -p /usr/local/bin \
    # Install dependencies.
    && export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    # Prefer packages in conda-forge
    && conda config --system --prepend channels conda-forge \
    # Packages in lower-priority channels not considered if a package with the same
    # name exists in a higher priority channel. Can dramatically speed up installations.
    # Conda recommends this as a default
    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html
    && conda config --set channel_priority strict \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    # Enable `conda activate`
    && conda init bash \
    # Clean up
    && sync && conda clean --all --yes && sync \
    && rm -rf ~/.cache/pip/* 
# Installing precomputed python packages
ENV FSLDIR="/opt/fsl-5.0.10" \
    PATH="/opt/fsl-5.0.10/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl-5.0.10/bin/fsltclsh" \
    FSLWISH="/opt/fsl-5.0.10/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libopenblas-base \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           nano \
           sudo \
           wget \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FSL ..." \
    && mkdir -p /opt/fsl-5.0.10 \
    && curl -fL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-5.0.10-centos6_64.tar.gz \
    | tar -xz -C /opt/fsl-5.0.10 --strip-components 1 \
    && echo "Installing FSL conda environment ..." \
    && bash /opt/fsl-5.0.10/etc/fslconf/fslpython_install.sh -f /opt/fsl-5.0.10 \
    && . ${FSLDIR}/etc/fslconf/fsl.sh \
    && PATH=${FSLDIR}/bin:${PATH} \
    && export FSLDIR PATH
    ENV . ${FSLDIR}/etc/fslconf/fsl.sh
    ENV PATH=${FSLDIR}/bin:${PATH}
    ENV export FSLDIR PATH
ENV OS="Linux" \
    PATH="/opt/freesurfer-7.1.1-min/bin:/opt/freesurfer-7.1.1-min/fsfast/bin:/opt/freesurfer-7.1.1-min/tktools:/opt/freesurfer-7.1.1-min/mni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    FREESURFER_HOME="/opt/freesurfer-7.1.1-min" \
    FREESURFER="/opt/freesurfer-7.1.1-min" \
    SUBJECTS_DIR="/opt/freesurfer-7.1.1-min/subjects" \
    LOCAL_DIR="/opt/freesurfer-7.1.1-min/local" \
    FSFAST_HOME="/opt/freesurfer-7.1.1-min/fsfast" \
    FMRI_ANALYSIS_DIR="/opt/freesurfer-7.1.1-min/fsfast" \
    FUNCTIONALS_DIR="/opt/freesurfer-7.1.1-min/sessions" \
    FS_OVERRIDE="0" \
    FIX_VERTEX_AREA="" \
    FSF_OUTPUT_FORMAT="nii.gz# mni env requirements" \
    MINC_BIN_DIR="/opt/freesurfer-7.1.1-min/mni/bin" \
    MINC_LIB_DIR="/opt/freesurfer-7.1.1-min/mni/lib" \
    MNI_DIR="/opt/freesurfer-7.1.1-min/mni" \
    MNI_DATAPATH="/opt/freesurfer-7.1.1-min/mni/data" \
    MNI_PERL5LIB="/opt/freesurfer-7.1.1-min/mni/share/perl5" \
    PERL5LIB="/opt/freesurfer-7.1.1-min/mni/share/perl5"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           libgomp1 \
           libxmu6 \
           libxt6 \
           perl \
           tcsh \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FreeSurfer ..." \
    && mkdir -p /opt/freesurfer-7.1.1-min \
    && curl -fL https://dl.dropbox.com/s/c3earkfhhvdyuo4/freesurfer-7.1.1-min.tgz \
    | tar -xz -C /opt/freesurfer-7.1.1-min --owner root --group root --no-same-owner --strip-components 1 \
         --exclude='average/mult-comp-cor' \
         --exclude='lib/cuda' \
         --exclude='lib/qt' \
         --exclude='subjects/V1_average' \
         --exclude='subjects/bert' \
         --exclude='subjects/cvs_avg35' \
         --exclude='subjects/cvs_avg35_inMNI152' \
         --exclude='subjects/fsaverage3' \
         --exclude='subjects/fsaverage4' \
         --exclude='subjects/fsaverage5' \
         --exclude='subjects/fsaverage6' \
         --exclude='subjects/fsaverage_sym' \
         --exclude='trctrain'
ENV ANTSPATH="/opt/ants-2.3.4/" \
    PATH="/opt/ants-2.3.4:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ca-certificates \
           curl \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading ANTs ..." \
    && mkdir -p /opt/ants-2.3.4 \
    && curl -fsSL https://dl.dropbox.com/s/gwf51ykkk5bifyj/ants-Linux-centos6_x86_64-v2.3.4.tar.gz \
    | tar -xz -C /opt/ants-2.3.4 --strip-components 1
ENV PATH="/opt/mrtrix3-3.0.2/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/mrtrix3-3.0.2/lib:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bzip2 \
           ca-certificates \
           curl \
           libpng16-16 \
           libtiff5 \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading MRtrix3 ..." \
    && mkdir -p /opt/mrtrix3-3.0.2 \
    && curl -fsSL https://github.com/MRtrix3/mrtrix3/releases/download/3.0.2/conda-linux-mrtrix3-3.0.2-h6bb024c_0.tar.bz2 \
    | tar -xj -C /opt/mrtrix3-3.0.2
#ENV PATH="/opt/miniconda-latest/bin/python3:$PATH"

# our ENV
COPY ["doTractography.py", "/work/run.py"]
RUN chmod +x /work/run.py
RUN apt-get update -y
RUN apt-get install libfftw3-dev -y
ENV . ${FSLDIR}/etc/fslconf/fsl.sh
ENV PATH=${FSLDIR}/bin:${PATH}
ENV export FSLDIR PATH
ENTRYPOINT ["python","./run.py"]
RUN ln -s -T /opt/miniconda-latest/bin/python3 /usr/local/bin/python 
WORKDIR /work  
RUN chmod 777 /work 